version: "3.5"
services:
  frontend:
    image: frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
  backend:
    image: backend
    container_name: backend
    restart: always
    ports:
      - 5000:5000
